spring:
  profiles:
    active:
      - EN
      - prod
      - dev
username: superuser
password: dbPassword
jdbcurl: someUrlForDB

---
spring:
  profiles: prod
username: superuserprod
password: dbPasswordprod
jdbcurl: someUrlForDBprod

